name: flutter_mvi_base
description: The MI parts of an MVI app.

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  todos_repository_base:
    path: ../todos_repository_base
  flutter_architecture_samples:
    path: ../..
  rxdart: 0.18.0

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
